name: bulls_eye
description: Your First Flutter App

dependencies:
    flutter:
        sdk: flutter
dev_dependencies:
    flutter_test:
        sdk: flutter
environment:
    sdk: '>=2.10.0 <3.0.0'

flutter:
    uses-material-design: true